/*********************************************************************
** Program name: Project 2
** Author: Jordan Hamilton
** Date: 10/18/2018
** Description:
*********************************************************************/

#include "Zoo.hpp"

/***********************************************************************************************
** Description: This program can be run via the project2 executable generated by make.
***********************************************************************************************/
int main() {

  Zoo newZoo;
  
  newZoo.play();

  return 0;

}
