/*********************************************************************
** Program name: Project 2
** Author: Jordan Hamilton
** Date: 10/18/2018
** Description:
*********************************************************************/

//#include "Zoo.hpp"
#include "Animal.hpp"
#include "Tiger.hpp"

#include <iostream>


/***********************************************************************************************
** Description: This program can be run via the project2 executable generated by make.
***********************************************************************************************/
int main() {

  //Zoo newZoo;
  //newZoo.play();
  Animal* tigger = new Tiger(4);
  std::cout << "Cost for this pointer: " << tigger->getCost() << std::endl;
  std::cout << "Base food cost for this pointer: " << tigger->getBaseFoodCost() << std::endl;
  std::cout << "Age for this pointer: " << tigger->getAge() << std::endl;
  std::cout << "Babies for this pointer: " << tigger->getNumberOfBabies() << std::endl;
  std::cout << "Payoff for this pointer: " << tigger->getPayoff() << std::endl;
  delete tigger;

  return 0;

}
